name: Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - run: yarn --frozen-lockfile
      - run: |
          echo ::add-matcher::.github/eslint.json
          yarn run eslint src test --format=compact
      - name: Run tests
        uses: koenhagen/measure-energy-action@v0.30
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: yarn test
          count: 900
      - run: yarn prepublishOnly
      - run: yarn docs:build
